hw_6
uralskiyart/geekshop-server pull request #6
Opened 2021-06-17 16:27 UTC by uralskiyart

2021-06-17 16:34 UTC, Vokler requested changes

2021-06-17 16:34 UTC, Vokler commented on baskets/views.py
> +def basket_edit(request, id, quantity):
А он же пустой) Нужно доработать

2021-06-17 21:08 UTC, uralskiyart commented on baskets/views.py
> +def basket_edit(request, id, quantity):
Ой ой. Я прошу прощения кидал в качестве заглушки чтобы потом поддержку не просить добавлять ссылку... Думал, что вы проверяете дз по утрам)

2021-06-18 07:23 UTC, Vokler approved these changes

2021-06-18 07:23 UTC, merged